# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_current:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run build

  # build_currentと重複が多いけどjobを小分けにして共通化すると遅くなるのでやらない
  # 正式公開されたらCircleCI2.1のcommandsを使ってもいいかも
  build_release:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout # チェックアウトは無駄だが鍵管理も行なっているので消さないこと
      - run: echo "export HOGE_HOGE=$(git describe)"
      - run: echo "export HOGE_HOGE=$(git describe)" >> $BASH_ENV
      - run: echo "$CIRCLE_BRANCH"
      - run:
          command: |
            git config --global user.email "circleci@example.com"
            git config --global user.name "circleci"
            # git checkout release
            # git pull
            # git merge origin/master -m "merge@CircleCI $HOGE_HOGE"
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              export TARGET_BRANCH=release
            else
              export TARGET_BRANCH=$(echo $CIRCLE_BRANCH | sed -e "s/-build$/-product/")
            fi
            echo $TARGET_BRANCH
            echo "export TARGET_BRANCH=$TARGET_BRANCH" >> $BASH_ENV

            # git checkout -B $TARGET_BRANCH
            if git checkout -q $TARGET_BRANCH; then
              echo pull
              git pull
              echo copy
              git checkout $CIRCLE_BRANCH .
            else
              echo create
              git checkout -b $TARGET_BRANCH
            fi
            sed -i -e "s/AAA = '.*'/AAA = '$HOGE_HOGE'/" a.txt
      - run: echo $HOGE_HOGE

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: echo $TARGET_BRANCH
      - run: npm run build
      - run: git add --all -v
      - run: git add --force -v dist/*
      - run: git commit -m "build@CircleCI $HOGE_HOGE"
      - run: git push -u origin $TARGET_BRANCH

workflows:
  version: 2
  pull_request:
    jobs:
      - build_current:
          filters:
            branches:
              ignore:
                - master
                - release
                - /^.+-build$/
                - /^.+-product$/
  release:
    jobs:
      - build_release:
          filters:
            branches:
              only:
                - master
                - /^.+-build$/
