# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  try_build:
    docker:
      - image: circleci/node:10.14
    branches:
      ignore:
        - master
        - build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run build

  merge_master:
    docker:
      - image: circleci/node:10.14
    branches:
      only:
        - master
    steps:
      - checkout
      - run: git config user.email "circleci@example.com"
      - run: git config user.name "circleci"
      - run: git checkout release
      - run: git pull
      - run: git merge origin/master -m "merge"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run build
      - run: git add --all -v
      - run: git add --force -v dist/*
      - run: git commit -m 'release'
      - run: git push
