# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_current:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run build

  # build_currentと重複が多いけどjobを小分けにして共通化すると遅くなるのでやらない
  # 正式公開されたらCircleCI2.1のcommandsを使ってもいいかも
  build_release:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout # チェックアウトは無駄だが鍵管理も行なっているので消さないこと
      - run: echo "export HOGE=$(git describe)"
      - run: echo "export HOGE=$(git describe)" >> $BASH_ENV
      - run:
          command: |
            git config user.email "circleci@example.com"
            git config user.name "circleci"
            git checkout release
            git pull
            git merge origin/master -m "merge@CircleCI $HOGE"
            sed -i -e "s/AAA = '.*'/AAA = '$HOGE'/" a.txt
      - run: echo $HOGE

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run build

      - run:
          command: |
            git add --all -v
            git add --force -v dist/*
            git commit -m "build@CircleCI $HOGE"
            git push

workflows:
  version: 2
  pull_request:
    jobs:
      - build_current:
          filters:
            branches:
              ignore:
                - master
                - release
  release:
    jobs:
      - build_release:
          filters:
            branches:
              only:
                - master
